# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bryan\Desktop\INICIO\QTDESIGNER\CrearQR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from os import close
import os,sys
import qrcode
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
from Libreria.RutaExactaPath import *

class Ui_Form_Crear(object):
    def setupUi(self, Form):
        Form.setObjectName("Ui_Form_Crear")
        Form.resize(859, 379)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(245, 0, 23, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 150, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(120, 50, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(110, 210, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.etUsuario = QtWidgets.QLineEdit(Form)
        self.etUsuario.setGeometry(QtCore.QRect(450, 150, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etUsuario.setFont(font)
        self.etUsuario.setStyleSheet("QLineEdit {\n"
        "      color: rgb(231, 231, 231);\n"
        "      font: 15pt \"Verdana\";\n"
        "      border: None;\n"
        "      border-bottom-color: white;\n"
        "      border-radius: 10px;\n"
        "      padding: 0 8px;\n"
        "      background: rgb(25, 25, 40);\n"
        "      selection-background-color: darkgray;\n"
        "}")
        self.etUsuario.setText("")
        self.etUsuario.setObjectName("etUsuario")
        self.etPassword = QtWidgets.QLineEdit(Form)
        self.etPassword.setGeometry(QtCore.QRect(450, 210, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etPassword.setFont(font)
        self.etPassword.setStyleSheet("QLineEdit {\n"
        "      color: rgb(231, 231, 231);\n"
        "      font: 15pt \"Verdana\";\n"
        "      border: None;\n"
        "      border-bottom-color: white;\n"
        "      border-radius: 10px;\n"
        "      padding: 0 8px;\n"
        "      background: rgb(25, 25, 40);\n"
        "      selection-background-color: darkgray;\n"
        "}")
        self.etPassword.setText("")
        self.etPassword.setObjectName("etPassword")
        self.btnGenerar = QtWidgets.QPushButton(Form)
        self.btnGenerar.setGeometry(QtCore.QRect(170, 260, 241, 51))
        self.btnGenerar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGenerar.setStyleSheet("QPushButton{\n"
        "color: rgb(48, 48, 48);\n"
        "font: 24pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnGenerar.setObjectName("btnGenerar")
        self.btnVolver = QtWidgets.QPushButton(Form)
        self.btnVolver.setGeometry(QtCore.QRect(430, 260, 241, 51))
        self.btnVolver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVolver.setStyleSheet("QPushButton{\n"
        "color: rgb(48, 48, 48);\n"
        "font: 24pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnVolver.setObjectName("btnVolver")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.btnGenerar.clicked.connect(self.GenerarQR)
        self.btnVolver.clicked.connect(Form.close)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Código del profesor ( usuario):"))
        self.label_42.setText(_translate("Form", "GENERADOR DE CODIGO QR"))
        self.label_7.setText(_translate("Form", "Contraseña de inicio de sesión:"))
        self.etUsuario.setPlaceholderText(_translate("Form", "Usuario de sesión"))
        self.etPassword.setPlaceholderText(_translate("Form", "Contraseña de sesión"))
        self.btnGenerar.setText(_translate("Form", "GENERAR QR"))
        self.btnVolver.setText(_translate("Form", "VOLVER"))
    def GenerarQR(self,Form):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        msg = QtWidgets.QMessageBox()
        #msg.setIcon(QtWidgets.QMessageBox.information)
        msg.setWindowTitle("AVISO")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        if (self.etUsuario.text()!="" and self.etPassword.text()!=""):
            qr.add_data(self.etUsuario.text()+"/"+self.etPassword.text())
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            filename = "Recursos/imagenes_QR_ACCESO/"+self.etUsuario.text()+".png"
            img.save("Recursos/imagenes_QR_ACCESO/"+self.etUsuario.text()+".png")
            msg.setText("Imagen QR creada para profesor de codigo "+self.etUsuario.text())
            msg.exec_()
            self.etUsuario.setText("")
            self.etPassword.setText("")
            path = resolver_ruta(filename)
            subprocess.Popen([path], shell=True)
        else:           
            msg.setText("Porfavor complete todas las casillas")
            msg.exec_()
