# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bryan\Desktop\INICIO\Menu_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from DataBase import Query
from os import close
import sys,os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt, pyqtSignal, QTimer
from PyQt5.QtGui import *
from Libreria.Execfile import *
from Libreria.CloseEvent import *
from Libreria.DetectorImagen import *
from Libreria.DetectorDiaSemana import *
from Interfaces.Inicio.Login import Ui_Dialog
from Interfaces.Menu.Seleccionar_Clase import Ui_Form as SeleccionForm
from Interfaces.Reportes.Reporte_AH import Ui_Form as ReporteAH
from Interfaces.Reportes.Reporte_AS import Ui_Form as ReporteAS
from Interfaces.Reportes.Reporte_LI import Ui_Form as ReporteLI
from Interfaces.Reportes.Reporte_RC import Ui_Form as ReporteRC
from Interfaces.Reportes.Reporte_RM import Ui_Form as ReporteRM
from Interfaces.Reportes.Reporte_RS import Ui_Form as ReporteRS

codigo_horario = ""
datos_enviados = []
class Ui_Form(object):
    def setupUi(self, Form,i,Dialog):
        global profesor
        profesor = i
        #------------------------
        datos_enviados.append(i[0])
        #------------------------
        Form.setObjectName("Form")
        Form.resize(1191, 651)
        #SIGUIENTE CODIGO ES PARA HACER UNICAMENTE VISIBLE MI INTERFACE
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        #----------------------------------------------------------------
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(180, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_41 = QtWidgets.QLabel(self.frame)#AQUI
        self.label_41.setGeometry(QtCore.QRect(20, 20, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbClase = QtWidgets.QLabel(self.frame)
        self.lbClase.setGeometry(QtCore.QRect(120, 80, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.lbClase.setFont(font)
        self.lbClase.setObjectName("lbClase")

        #self.iconUser = QtWidgets.QLabel(self.frame)
        #self.iconUser = QLabelClickable(self)
        self.iconUser = QLabel(Form)

        self.iconUser.setGeometry(QtCore.QRect(1110, 10, 61, 71))
        self.iconUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iconUser.setStyleSheet("")
        self.iconUser.setText("")
        self.iconUser.setPixmap(QtGui.QPixmap("Recursos/imagenes/user.png"))
        self.iconUser.setObjectName("iconUser")
        self.iconSeccion = QtWidgets.QLabel(self.frame)
        self.iconSeccion.setGeometry(QtCore.QRect(1020, 10, 61, 71))
        self.iconSeccion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iconSeccion.setText("")
        self.iconSeccion.setPixmap(QtGui.QPixmap("Recursos/imagenes/file.png"))
        self.iconSeccion.setObjectName("iconSeccion")
        self.lbAsistencia = QtWidgets.QLabel(self.frame)
        self.lbAsistencia.setEnabled(False)
        self.lbAsistencia.setGeometry(QtCore.QRect(30, 160, 341, 331))
        self.lbAsistencia.setText("")
        self.lbAsistencia.setPixmap(QtGui.QPixmap("Recursos/imagenes/marcar_asistencia.png"))
        self.lbAsistencia.setObjectName("lbAsistencia")
        self.lbAsistencia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbReporteAS = QtWidgets.QLabel(self.frame)
        self.lbReporteAS.setEnabled(False)
        self.lbReporteAS.setGeometry(QtCore.QRect(500, 140, 251, 111))
        self.lbReporteAS.setText("")
        self.lbReporteAS.setPixmap(QtGui.QPixmap("Recursos/imagenes/r1.jpg"))
        self.lbReporteAS.setObjectName("lbReporteAS")
        self.lbReporteAS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbReporteAH = QtWidgets.QLabel(self.frame)
        self.lbReporteAH.setEnabled(False)
        self.lbReporteAH.setGeometry(QtCore.QRect(780, 140, 251, 111))
        self.lbReporteAH.setText("")
        self.lbReporteAH.setPixmap(QtGui.QPixmap("Recursos/imagenes/r2.png"))
        self.lbReporteAH.setObjectName("lbReporteAH")
        self.lbReporteAH.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbResumenS = QtWidgets.QLabel(self.frame)
        self.lbResumenS.setEnabled(False)
        self.lbResumenS.setGeometry(QtCore.QRect(500, 280, 251, 111))
        self.lbResumenS.setText("")
        self.lbResumenS.setPixmap(QtGui.QPixmap("Recursos/imagenes/r3.png"))
        self.lbResumenS.setObjectName("lbResumenS")
        self.lbResumenS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbRankingC = QtWidgets.QLabel(self.frame)
        self.lbRankingC.setEnabled(False)
        self.lbRankingC.setGeometry(QtCore.QRect(780, 280, 251, 111))
        self.lbRankingC.setText("")
        self.lbRankingC.setPixmap(QtGui.QPixmap("Recursos/imagenes/r4.png"))
        self.lbRankingC.setObjectName("lbRankingC")
        self.lbRankingC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbRankingM = QtWidgets.QLabel(self.frame)
        self.lbRankingM.setEnabled(False)
        self.lbRankingM.setGeometry(QtCore.QRect(500, 420, 251, 111))
        self.lbRankingM.setText("")
        self.lbRankingM.setPixmap(QtGui.QPixmap("Recursos/imagenes/r5.png"))
        self.lbRankingM.setObjectName("lbRankingM")
        self.lbRankingM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbListaI = QtWidgets.QLabel(self.frame)
        self.lbListaI.setEnabled(False)
        self.lbListaI.setGeometry(QtCore.QRect(780, 420, 251, 111))
        self.lbListaI.setText("")
        self.lbListaI.setPixmap(QtGui.QPixmap("Recursos/imagenes/r6.png"))
        self.lbListaI.setObjectName("lbListaI")
        self.lbListaI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_42 = QtWidgets.QLabel(self.frame)
        self.label_42.setGeometry(QtCore.QRect(690, 90, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.qWUser = QtWidgets.QWidget(self.frame)
        self.qWUser.setEnabled(True)
        self.qWUser.setGeometry(QtCore.QRect(960, 90, 211, 81))
        self.qWUser.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.qWUser.setObjectName("qWUser")
        self.lbProfesor = QtWidgets.QPushButton(self.qWUser)
        self.lbProfesor.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbProfesor.setFont(font)
        self.lbProfesor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbProfesor.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 10pt \"Verdana\";\n"
        "border: 2px solid #aa0000;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "cursor:pointer;\n"
        "}")
        self.lbProfesor.setObjectName("lbProfesor")
        self.btnCerrarSesionUser = QtWidgets.QPushButton(self.qWUser)
        self.btnCerrarSesionUser.setGeometry(QtCore.QRect(0, 40, 211, 41))
        self.btnCerrarSesionUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrarSesionUser.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 10pt \"Verdana\";\n"
        "border: 2px solid #55BEEF;\n"
        "padding: 5px;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(85, 190, 239);\n"
        "}")
        self.retranslateUi(Form,i)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btnCerrarSesionUser.setObjectName("btnCerrarSesionUser")
        
        self.lbOculto = QtWidgets.QLabel(self.frame)
        self.lbOculto.setText("")
        self.lbOculto.setObjectName("lbOculto")
        self.lbOculto.setVisible(False)
        global codigo_dia_clase
        codigo_dia_clase = 0


        self.iconUser.mousePressEvent = self.mostrarOpciones
        self.iconSeccion.mousePressEvent = self.mostrarClase
        self.btnCerrarSesionUser.clicked.connect(Form.close)
        self.btnCerrarSesionUser.clicked.connect(Dialog.show)

        global codigo_horario_seleccionado
        codigo_horario_seleccionado = self.lbOculto


        global clase_de_profesor
        clase_de_profesor = self.lbClase

        global Asistencia_Imagen
        global Reporte_1
        global Reporte_2
        global Reporte_3
        global Reporte_4
        global Reporte_5
        global Reporte_6

        Asistencia_Imagen = self.lbAsistencia
        Reporte_1 = self.lbReporteAS
        Reporte_2 = self.lbReporteAH
        Reporte_3 = self.lbResumenS
        Reporte_4 = self.lbRankingC
        Reporte_5 = self.lbRankingM
        Reporte_6 = self.lbListaI

        self.lbAsistencia.mousePressEvent = self.TomarAsistencia
        self.lbReporteAS.mousePressEvent = self.ReportePressAS
        self.lbReporteAH.mousePressEvent = self.ReportePressAH
        self.lbResumenS.mousePressEvent = self.ReportePressS
        self.lbRankingC.mousePressEvent = self.ReportePressC
        self.lbRankingM.mousePressEvent = self.ReportePressM
        self.lbListaI.mousePressEvent = self.ReportePressI

    def retranslateUi(self, Form,i):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_41.setText(_translate("Form", "Menú Principal"))
        self.label_2.setText(_translate("Form", "Clase:"))
        self.lbClase.setText(_translate("Form", "Seleccione una clase"))
        self.label_42.setText(_translate("Form", "Reportes"))
        self.lbProfesor.setText(_translate("Form", i[1]))
        self.btnCerrarSesionUser.setText(_translate("Form", "Cerrar Sesión"))
        self.qWUser.hide()

    def mostrarOpciones(self,Form):
        '''visibilidad_icoUser = str(self.qWUser.isVisible())
        print(visibilidad_icoUser)'''
        if self.qWUser.isVisible() == False:
            self.qWUser.show()
        else:
            self.qWUser.hide()
    
    def mostrarClase(self,Form):
        self.menu = QtWidgets.QMainWindow()
        self.ui = SeleccionForm()
        self.ui.setupUi(self.menu,profesor)
        self.menu.show()

    def ReportePressAS(self,Form):
        self.report = QtWidgets.QMainWindow()
        self.ui = ReporteAS()
        self.ui.setupUi(self.report,datos_enviados)
        self.report.show()
    def ReportePressAH(self,Form):
        self.report = QtWidgets.QMainWindow()
        self.ui = ReporteAH()
        self.ui.setupUi(self.report,datos_enviados)
        self.report.show()
    def ReportePressS(self,Form):
        self.report = QtWidgets.QMainWindow()
        self.ui = ReporteRS()
        self.ui.setupUi(self.report,datos_enviados)
        self.report.show()
    def ReportePressC(self,Form):
        self.report = QtWidgets.QMainWindow()
        self.ui = ReporteRC()
        self.ui.setupUi(self.report,datos_enviados)
        self.report.show()
    def ReportePressM(self,Form):
        self.report = QtWidgets.QMainWindow()
        self.ui = ReporteRM()
        self.ui.setupUi(self.report,datos_enviados)
        self.report.show()
    def ReportePressI(self,Form):
        self.report = QtWidgets.QMainWindow()
        self.ui = ReporteLI()
        self.ui.setupUi(self.report,datos_enviados)
        self.report.show()

    def TomarAsistencia(self,Form):
        AsistenciaAlumno = IdentificadorImagen('Recursos/Reconocimiento/Fotos','Recursos/Reconocimiento/Modelos/modeloLBPHFace.xml',"Rostro")
        comprobar_codigo_exista = Query.identificar_alumno(str(AsistenciaAlumno))
        if AsistenciaAlumno != "Falla":
            if len(comprobar_codigo_exista)>0:
                uhe = time.strftime("%H:%M:%S")
                fecha = str(time.strftime("20%y-%m-%d"))
                
                curso_sin_seccion = self.lbClase.text()[:-1]
                alumno_apto_clase = Query.identificar_alumno_apto(curso_sin_seccion,str(AsistenciaAlumno))
                nombre_alumno = Query.obtener_nombre_alumno(str(AsistenciaAlumno))
                alumno_marco_asistencia = Query.identificar_alumno_marco(self.lbOculto.text(),fecha,str(AsistenciaAlumno))
                print(alumno_marco_asistencia)
                print(self.lbOculto.text(),fecha,str(AsistenciaAlumno))
                alumno_pertenece_clase = Query.alumno_pertenece_seccion(str(AsistenciaAlumno),self.lbClase.text())
                texto =""
                if len(alumno_apto_clase)>0:
                    if len(alumno_marco_asistencia)>0:
                        texto = "El alumno "+nombre_alumno+" no puede marcar 2 veces asistencia"
                    else:
                        if len(alumno_pertenece_clase)>0:
                            texto = "Asistencia correcta del alumno "+nombre_alumno
                            Query.insertar_asistencia(str(AsistenciaAlumno),self.lbOculto.text(),uhe,fecha)
                        else:
                            winsound.PlaySound("SystemExclamation", winsound.SND_ALIAS)
                            texto = "Alumno "+nombre_alumno+" será registrado como alumno invitado"
                            Query.insertar_asistencia(str(AsistenciaAlumno),self.lbOculto.text(),uhe,fecha)
                    engine.say(texto)
                    engine.runAndWait()
                else:
                    error_dialog.showMessage('Alumno no es apto para tomar esta clase')
            elif str(AsistenciaAlumno) !="":
                error_dialog.showMessage('Alumno no existe')
        else:
            error_dialog.showMessage('Su cámara esta mal conectada o no conectada')

def completarClase(clase,codigoH):
    #-----------------------------
    datos_enviados.append(clase.rstrip(clase[-1]))
    datos_enviados.append(clase)
    #print(2)
    #-----------------------------
    codigo_horario = codigoH
    clase_de_profesor.setText(clase)
    

def completarOculto(codigo_horario_clase):
    #-----------------------------
    datos_enviados.append(codigo_horario_clase)
    #print(3)
    #-----------------------------
    codigo_horario_seleccionado.setText(codigo_horario_clase)
    
    activarLabel(codigo_horario_clase)

def activarLabel(codigo_horario_clase_seleccionada):
    uhe = time.strftime("%H:%M:%S")
    fecha = str(time.strftime("20%y-%m-%d"))
    dia_semana = deteccion_dia_semana(fecha,'%Y-%m-%d')
    #lista_dias_clase = Query.dias_dictados_clase(clase_de_profesor.text(),profesor[0])
    dia_clase_de_codigo = Query.dia_clase_codigo(codigo_horario_clase_seleccionada)
    #if(len(dia_clase_de_codigo)>0):
    if dia_clase_de_codigo[0][0] == dia_semana:
        Asistencia_Imagen.setEnabled(True)
    else:
        Asistencia_Imagen.setEnabled(False)
        error_dialog.showMessage('EL DIA DE HOY NO PUEDE TOMAR ASISTENCIA EN ESTA SECCION')
    #else:
    #    error_dialog.showMessage('Error en las listas')
    Reporte_1.setEnabled(True)
    Reporte_2.setEnabled(True)
    Reporte_3.setEnabled(True)
    Reporte_4.setEnabled(True)
    Reporte_5.setEnabled(True)
    Reporte_6.setEnabled(True)




'''if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())'''
