# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bryan\Desktop\INICIO\Seleccionar_Clase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from os import close
from PyQt5 import QtCore, QtGui, QtWidgets
from DataBase import Query
import Interfaces.Menu.Menu_Principal as CursoSeleccionado


class Ui_Form(object):
    def setupUi(self, Form,i):
        global profesor
        profesor = i
        Form.setObjectName("Form")
        Form.resize(401, 300)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(21, 109, 169, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(30, 20, 341, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.cbSeleccionarC = QtWidgets.QComboBox(Form)
        self.cbSeleccionarC.setEnabled(True)
        self.cbSeleccionarC.setGeometry(QtCore.QRect(140, 80, 191, 31))
        self.cbSeleccionarC.setStyleSheet("")
        self.cbSeleccionarC.setEditable(False)
        self.cbSeleccionarC.setObjectName("cbSeleccionarC")
        self.cbSeleccionarF = QtWidgets.QComboBox(Form)
        #self.cbSeleccionarF.setEnabled(False)
        self.cbSeleccionarF.setGeometry(QtCore.QRect(140, 130, 191, 31))
        self.cbSeleccionarF.setStyleSheet("")
        self.cbSeleccionarF.setEditable(False)
        self.cbSeleccionarF.setObjectName("cbSeleccionarF")
        self.btnAceptar = QtWidgets.QPushButton(Form)
        self.btnAceptar.setGeometry(QtCore.QRect(60, 190, 121, 41))
        self.btnAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAceptar.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 17pt \"Verdana\";\n"
        "border: 2px solid #55BEEF;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(85, 190, 239);\n"
        "}")
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCerrar = QtWidgets.QPushButton(Form)
        self.btnCerrar.setGeometry(QtCore.QRect(210, 190, 121, 41))
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrar.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 17pt \"Verdana\";\n"
        "border: 2px solid #55BEEF;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(85, 190, 239);\n"
        "}")
        self.btnCerrar.setObjectName("btnCerrar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 85, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        global comboClase
        global comboFecha
        comboClase = self.cbSeleccionarC
        comboFecha = self.cbSeleccionarF
        '''sql = "Select
        model = cn."'''
        lista_clases = Query.cursos_profesor(profesor[0])
        comboClase.addItems(lista_clases)
        lista_Horario = Query.codigo_horario_clase(profesor[0],lista_clases[0])

        inicial_combo_horario = []
        for i in lista_Horario:
            dato = str(i[1])+" "+str(i[4])+" "+str(i[2])+"-"+str(i[3])
            inicial_combo_horario.append(dato)

        comboFecha.addItems(inicial_combo_horario)

        comboClase.currentTextChanged.connect(self.ComboPress)
        self.btnAceptar.clicked.connect(self.enviar)
        self.btnAceptar.clicked.connect(Form.close)
        self.btnCerrar.clicked.connect(Form.close)
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_41.setText(_translate("Form", "SELECCIONAR CLASE Y FECHA"))
        self.btnAceptar.setText(_translate("Form", "ACEPTAR"))
        self.btnCerrar.setText(_translate("Form", "CERRAR"))
        self.label_2.setText(_translate("Form", "CLASE:"))
        self.label_3.setText(_translate("Form", "FECHA:"))
    
    def enviar(self,Form):
        CursoSeleccionado.completarClase(comboClase.currentText(),profesor[1])
        horario_seleccionado_combo = Query.codigo_horario_claseNum(profesor[0],comboClase.currentText())
        position = comboFecha.currentIndex()
        CursoSeleccionado.completarOculto(str(horario_seleccionado_combo[position][0]))
        
    def ComboPress(self,Form):
        lista_Horario = Query.codigo_horario_clase(profesor[0],comboClase.currentText())
        info_hor_clas = []
        global cod_hor_clas
        cod_hor_clas = []
        for i in lista_Horario:
            dato = str(i[1])+" "+str(i[4])+" "+str(i[2])+"-"+str(i[3])
            info_hor_clas.append(dato)
            cod_hor_clas.append(str(i[0]))

        comboFecha.clear()
        comboFecha.addItems(info_hor_clas)


'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())'''
