# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bryan\Desktop\INICIO\QTDESIGNER\Reporte_AS.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from numpy.linalg import qr
from DataBase import Query
from datetime import datetime, timedelta
from Libreria.DetectorSemanas import *
from Libreria.ExportarTablaPDF import *
from Libreria.ExportarTablaExcel import *
from PyQt5 import QtCore, QtGui, QtWidgets,QtPrintSupport
from PyQt5.QtCore import Qt, QSortFilterProxyModel
from PyQt5.QtGui import QStandardItemModel, QStandardItem



class Ui_Form(object):
    def setupUi(self, Form,datos_obtenidos):
        global data_obtenida
        data_obtenida = datos_obtenidos

        Form.setObjectName("Form")
        Form.resize(1191, 653)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(245, 0, 23, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lbClase = QtWidgets.QLabel(Form)
        self.lbClase.setGeometry(QtCore.QRect(110, 80, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(14)
        self.lbClase.setFont(font)
        self.lbClase.setObjectName("lbClase")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setGeometry(QtCore.QRect(20, 10, 841, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(420, 120, 331, 41))
        self.label_2.setStyleSheet("border: 2px solid #fd0000;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.rbAsistencia = QtWidgets.QRadioButton(Form)
        self.rbAsistencia.setGeometry(QtCore.QRect(470, 130, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rbAsistencia.setFont(font)
        self.rbAsistencia.setStyleSheet("")
        self.rbAsistencia.setChecked(True)
        self.rbAsistencia.setObjectName("rbAsistencia")

        global qrbAsistencia
        qrbAsistencia = self.rbAsistencia

        self.rbInasistencia = QtWidgets.QRadioButton(Form)
        self.rbInasistencia.setGeometry(QtCore.QRect(590, 130, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rbInasistencia.setFont(font)
        self.rbInasistencia.setStyleSheet("")
        self.rbInasistencia.setObjectName("rbInasistencia")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cbSemana = QtWidgets.QComboBox(Form)
        self.cbSemana.setGeometry(QtCore.QRect(190, 190, 191, 22))
        self.cbSemana.setObjectName("cbSemana")

        global qsemana
        qsemana=self.cbSemana

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(430, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.etBuscar = QtWidgets.QLineEdit(Form)
        self.etBuscar.setGeometry(QtCore.QRect(600, 190, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etBuscar.setFont(font)
        self.etBuscar.setStyleSheet("QLineEdit {\n"
        "      color: rgb(231, 231, 231);\n"
        "      font: 12pt \"Verdana\";\n"
        "      border: None;\n"
        "      border-bottom-color: white;\n"
        "      border-radius: 10px;\n"
        "      padding: 0 8px;\n"
        "      background: rgb(217, 26, 58);\n"
        "      selection-background-color: darkgray;\n"
        "}")
        self.etBuscar.setObjectName("etBuscar")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(310, 240, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lbSemana = QtWidgets.QLabel(Form)
        self.lbSemana.setGeometry(QtCore.QRect(440, 240, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.lbSemana.setFont(font)
        self.lbSemana.setObjectName("lbSemana")
        self.tbAsistencia = QtWidgets.QTableWidget(Form)
        self.tbAsistencia.setGeometry(QtCore.QRect(120, 270, 751, 321))
        self.tbAsistencia.setStyleSheet("")
        self.tbAsistencia.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbAsistencia.setAlternatingRowColors(False)
        self.tbAsistencia.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbAsistencia.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbAsistencia.setObjectName("tbAsistencia")
        self.tbAsistencia.setColumnCount(4)
        self.tbAsistencia.setRowCount(0)
        self.tbAsistencia.SelectionBehavior()

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        item.setFont(font)
        self.tbAsistencia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbAsistencia.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbAsistencia.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbAsistencia.setHorizontalHeaderItem(3, item)
        self.tbAsistencia.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)

        global qtabla
        qtabla = self.tbAsistencia
        
        self.btnAbrirRE = QtWidgets.QPushButton(Form)
        self.btnAbrirRE.setGeometry(QtCore.QRect(220, 600, 241, 31))
        self.btnAbrirRE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAbrirRE.setStyleSheet("QPushButton{\n"
        "color: rgb(48, 48, 48);\n"
        "font: 12pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnAbrirRE.setObjectName("btnAbrirRE")
        self.btnImprimir = QtWidgets.QPushButton(Form)
        self.btnImprimir.setGeometry(QtCore.QRect(500, 600, 241, 31))
        self.btnImprimir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnImprimir.setStyleSheet("QPushButton{\n"
        "color: rgb(48, 48, 48);\n"
        "font: 12pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnImprimir.setObjectName("btnImprimir")
        self.btnVolver = QtWidgets.QPushButton(Form)
        self.btnVolver.setGeometry(QtCore.QRect(910, 450, 241, 131))
        self.btnVolver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVolver.setStyleSheet("QPushButton{\n"
        "color: rgb(48, 48, 48);\n"
        "font: 24pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnVolver.setObjectName("btnVolver")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cbPeriodo = QtWidgets.QComboBox(Form)
        self.cbPeriodo.setGeometry(QtCore.QRect(110, 140, 131, 22))
        self.cbPeriodo.setObjectName("cbPeriodo")

        global ComboPeriodo
        ComboPeriodo = self.cbPeriodo

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 120, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("lbPeriodoActual")
        self.lbPeriodoActual = QtWidgets.QLabel(Form)
        self.lbPeriodoActual.setGeometry(QtCore.QRect(150, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        self.lbPeriodoActual.setFont(font)
        self.lbPeriodoActual.setObjectName("lbPeriodoActual")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        fecha_actual = format(datetime.today().year)+"-"+format(datetime.today().month)+"-"+format(datetime.today().day)

        #INGRESAREMOS EL VALOR DE LA CLASE SELECCIONADA
        #------------------------------------------------
        self.lbClase.setText(datos_obtenidos[2])
        #OBTENDREMOS LA LISTA DE PERIODO LLENADO POR PRIMERA VEZ
        #------------------------------------------------
        lista_periodo = Query.informacion_periodo()
        descripcion_periodo = []
        for i in lista_periodo:
            descripcion_periodo.append(i[1])
        self.cbPeriodo.addItems(descripcion_periodo)
        #------------------------------------------------------
        #OBTENDREMOS LA LISTA DE SEMANA LLENADO POR PRIMERA VEZ
        #--------------------------------------------------------
        lista_semana = deteccion_semanas(lista_periodo[0][2],lista_periodo[0][3],'%Y-%m-%d')
        semana_inicial = []
        for i in range(lista_semana):
            semana_inicial.append("Semana "+str(i+1))
        self.cbSemana.addItems(semana_inicial)
        #--------------------------------------------------------
        #INGRESAREMOS EL VALOR DEL PERIODO ACTUAL Y SEMANA ACTUAL
        datos_semana_actual = identificarSemanaActual(lista_periodo,fecha_actual)
        self.lbPeriodoActual.setText(datos_semana_actual[0])
        self.lbSemana.setText(datos_semana_actual[1])
        #--------------------------------------------------------
        #LLENADO DE TABLA PRIMERA VEZ
        global alumnos_clase_periodoAS
        alumnos_clase_periodoAS = Query.alumnos_clase_periodo(datos_obtenidos[2],self.cbPeriodo.currentText())
        
        alumnos_de_reporte_as_asistencia = SepararListaAlumnosReporteAS(self.rbAsistencia.isChecked())
        
        self.tbAsistencia.setRowCount(len(alumnos_de_reporte_as_asistencia))
        for a in range(len(alumnos_de_reporte_as_asistencia)):
            for b in range(len(alumnos_de_reporte_as_asistencia[0])):
                self.tbAsistencia.setItem(a,b, QtWidgets.QTableWidgetItem(alumnos_de_reporte_as_asistencia[a][b]))
        self.tbAsistencia.resizeColumnsToContents()

        #-------------------------------
        #AL DAR SELECCION EN ALGUN ASISTENCIA E INASISTENCIA
        self.rbInasistencia.toggled.connect(self.completar_tabla_inasistencia)
        #----------------------------------
        #AL SELECCIONAR UN COMBO BOX 
        self.cbPeriodo.currentTextChanged.connect(self.PresionarPeriodo)
        #print(self.cbSemana.currentText())
        #if(self.cbSemana.currentIndex() !=0):
        global valor_dejado_periodo
        valor_dejado_periodo = []
        valor_dejado_periodo.append(self.cbPeriodo.currentText())

        self.cbSemana.currentTextChanged.connect(self.PresionarSemana)
        #self.rbInasistencia.clicked = self.completar_tabla_inasistencia
        #-----------------------------
        #AL DAR CLICK EN LA BUSQUEDA
        global tabla_inicial
        tabla_inicial = []

        self.etBuscar.textChanged.connect(self.BuscarTabla)
        #Dar CLICK EN IMPRIMIR
        #------------------------------------
        self.btnImprimir.clicked.connect(self.ImprimirTabla)
        #------------------------------------
        #Dar CLICK EN BOTON PARA EXCEL
        #------------------------------------
        self.btnAbrirRE.clicked.connect(self.ExportarExcel)
        #------------------------------------
        #DAR CLICK EN VOLVER
        self.btnVolver.clicked.connect(Form.close)
        #------------------------------
        #print(Query.dias_clase(self.lbClase.text()))
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Clase:"))
        self.lbClase.setText(_translate("Form", "Seleccione una clase"))
        self.label_42.setText(_translate("Form", "REPORTE DE ALUMNOS POR SEMANA"))
        self.rbAsistencia.setText(_translate("Form", "Asistencia"))
        self.rbInasistencia.setText(_translate("Form", "Inasistencia"))
        self.label_4.setText(_translate("Form", "Buscar por semana:"))
        self.label_5.setText(_translate("Form", "Buscar por alumno:"))
        self.etBuscar.setPlaceholderText(_translate("Form", "Alumno a buscar"))
        self.label_6.setText(_translate("Form", "Semana actual:"))
        self.lbSemana.setText(_translate("Form", "Sin selección de semana"))
        item = self.tbAsistencia.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tbAsistencia.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Alumno"))
        item = self.tbAsistencia.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Asistencia"))
        item = self.tbAsistencia.horizontalHeaderItem(3)
        item.setText(_translate("Form", "% de asistencia"))
        self.btnAbrirRE.setText(_translate("Form", "ABRIR REPORTE EN EXCEL"))
        self.btnImprimir.setText(_translate("Form", "IMPRIMIR"))
        self.btnVolver.setText(_translate("Form", "VOLVER"))
        self.label_7.setText(_translate("Form", "Periodo:"))
        self.label_8.setText(_translate("Form", "Periodo Actual:"))
        self.lbPeriodoActual.setText(_translate("Form", "Selecciona"))

    def PresionarPeriodo(self,Form):
        semana = []
        lista_Horario = Query.informacion_periodo_seleccionado(str(self.cbPeriodo.currentText()))
        for i in lista_Horario:
            semana_detectada = deteccion_semanas(i[2],i[3],'%Y-%m-%d')
            for i in range(semana_detectada):
                semana.append("Semana "+str(i+1))
            #print(self.cbSemana.currentText())
        #self.cbSemana.disconnect(True)
        
        self.cbSemana.clear()
        self.cbSemana.addItems(semana)
        if(len(valor_dejado_periodo)==0):
            valor_dejado_periodo.append(self.cbPeriodo.currentText())
        else:
            valor_dejado_periodo[0] = self.cbPeriodo.currentText()

        completarTablaPeriodo()

    def PresionarSemana(self,Form):
        if(len(valor_dejado_periodo)!=0):
            if(self.cbPeriodo.currentText() == valor_dejado_periodo[0]):
                completarTablaSemana()

    def completar_tabla_inasistencia(self,Form):
        self.tbAsistencia.clearContents()

        alumnos_de_reporte_as_inasistencia = SepararListaAlumnosReporteAS(self.rbAsistencia.isChecked())
        
        self.tbAsistencia.setRowCount(len(alumnos_de_reporte_as_inasistencia))
        for a in range(len(alumnos_de_reporte_as_inasistencia)):
            for b in range(len(alumnos_de_reporte_as_inasistencia[0])):
                self.tbAsistencia.setItem(a,b, QtWidgets.QTableWidgetItem(alumnos_de_reporte_as_inasistencia[a][b]))
        self.tbAsistencia.resizeColumnsToContents()
    
    def BuscarTabla(self,Form):
        name = self.etBuscar.text().lower()
        for row in range(self.tbAsistencia.rowCount()):
            item = self.tbAsistencia.item(row, 1)
            # if the search is *not* in the item's text *do not hide* the row
            self.tbAsistencia.setRowHidden(row, name not in item.text().lower())

    def ImprimirTabla(self,Form):
        exportarPDF(qtabla,"ReporteAS.("+ComboPeriodo.currentText()+")."+qsemana.currentText())
    
    def ExportarExcel(self,Form):
        cabezera = cabezeraActualTabla()
        lista_tabla_actual = listaActualTabla()
        exportarExcel(lista_tabla_actual,cabezera,"ReporteAS.("+ComboPeriodo.currentText()+")."+qsemana.currentText())

def identificarSemanaActual(lista_periodo,fecha_actual):
    datos_semana = []
    for i in lista_periodo:
        if(fecha_actual>=i[2] and fecha_actual<= i[3]):
            semana_actual = deteccion_semanas(i[2],fecha_actual,'%Y-%m-%d')
            #semana_actual = int((fecha_actual-i[2])/7)
            datos_semana.append(i[1])
            datos_semana.append(str(semana_actual+1))
            return datos_semana
    return datos_semana

def SepararListaAlumnosReporteAS(activado_asistencia):
    alumnos_de_reporte_as = []
    alumnos_clase_periodo = Query.alumnos_clase_periodo(data_obtenida[2],ComboPeriodo.currentText())
    semana_numero_int = [int(temp)for temp in qsemana.currentText().split() if temp.isdigit()]
    if len(alumnos_clase_periodo)>0:
        for a in range(len(alumnos_clase_periodo)):
            lista_separada=[]
            lista_separada.append(alumnos_clase_periodo[a][0])
            lista_separada.append(alumnos_clase_periodo[a][1])
            #print(datos_obtenidos[2],periodo,alumnos_clase_periodo[a][0],semana_numero_int)
            
            maximo_semana = Query.cantidad_veces_clase_maximo_semana(data_obtenida[2])
            asistencia_acumulada = Query.cantidad_acumulada_asistencia_semana_alumno(data_obtenida[2],ComboPeriodo.currentText(),alumnos_clase_periodo[a][0],semana_numero_int[0])
            maximo_actual = maximo_semana * semana_numero_int[0]
            valor_activado = asistencia_acumulada/maximo_actual
            valor_desactivado = 1-(asistencia_acumulada/maximo_actual)
            #formula_porcentaje = round((asistencia_acumulada/maximo_semana*semana_numero_int)*100,2)
            _translate = QtCore.QCoreApplication.translate
            if activado_asistencia == True:
                lista_separada.append(str(asistencia_acumulada))
                formula_porcentaje = round(valor_activado*100,2)
                lista_separada.append(str(formula_porcentaje)+"%")

                item = qtabla.horizontalHeaderItem(2)
                item.setText(_translate("Form", "Asistencia"))
                item = qtabla.horizontalHeaderItem(3)
                item.setText(_translate("Form", "% de asistencia"))
            else:
                lista_separada.append(str(maximo_actual-asistencia_acumulada))
                formula_porcentaje = round(valor_desactivado*100,2)
                lista_separada.append(str(formula_porcentaje)+"%")

                item = qtabla.horizontalHeaderItem(2)
                item.setText(_translate("Form", "Inasistencia"))
                item = qtabla.horizontalHeaderItem(3)
                item.setText(_translate("Form", "% de inasistencia"))
            alumnos_de_reporte_as.append(lista_separada)
    return alumnos_de_reporte_as

def completarTablaPeriodo():
    qtabla.clearContents()
    
    alumnos_de_reporte_as_inasistencia = SepararListaAlumnosReporteAS(qrbAsistencia.isChecked())
    qtabla.setRowCount(len(alumnos_de_reporte_as_inasistencia))
    for a in range(len(alumnos_de_reporte_as_inasistencia)):
        for b in range(len(alumnos_de_reporte_as_inasistencia[0])):
            qtabla.setItem(a,b, QtWidgets.QTableWidgetItem(alumnos_de_reporte_as_inasistencia[a][b]))
    qtabla.resizeColumnsToContents()

def completarTablaSemana():
    qtabla.clearContents()
    alumnos_clase_periodoAS = Query.alumnos_clase_periodo(data_obtenida[2],ComboPeriodo.currentText())

    alumnos_de_reporte_as_inasistencia = SepararListaAlumnosReporteAS(qrbAsistencia.isChecked())

    qtabla.setRowCount(len(alumnos_de_reporte_as_inasistencia))

    for a in range(len(alumnos_de_reporte_as_inasistencia)):

        for b in range(len(alumnos_de_reporte_as_inasistencia[0])):

            qtabla.setItem(a,b, QtWidgets.QTableWidgetItem(alumnos_de_reporte_as_inasistencia[a][b]))
    qtabla.resizeColumnsToContents()

def listaActualTabla():
    rows = qtabla.rowCount()
    for n in range(rows):
        fila=[]
        for column in range(qtabla.model().columnCount()):
            fila.append(qtabla.item(n, column).text())
        tabla_inicial.append(fila)
    return tabla_inicial

def cabezeraActualTabla():
    cabezera_obtenido = []
    for i in range(qtabla.model().columnCount()):
        label = qtabla.horizontalHeaderItem(i).text()
        cabezera_obtenido.append(label)
    return cabezera_obtenido

