# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bryan\Desktop\INICIO\QT DESIGNER\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import datetime,os,sys
from Interfaces.Menu.Menu_Principal import *
from Interfaces.Inicio.EXTRAS.CrearQR import *
from DataBase import Query
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QTime, QTimer
from PyQt5.QtWidgets import *
from Libreria.DetectorImagen import *



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1189, 649)
        #SIGUIENTE CODIGO ES PARA HACER UNICAMENTE VISIBLE MI INTERFACE
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        #----------------------------------------------------------------
        self.FrameLogin = QtWidgets.QFrame(Dialog)
        self.FrameLogin.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.FrameLogin.setStyleSheet("background-color: rgb(232,137,137 );")
        self.FrameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameLogin.setObjectName("FrameLogin")
        self.label = QtWidgets.QLabel(self.FrameLogin)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Recursos/imagenes/uni.jpg"))
        self.label.setObjectName("label")
        self.widget_6 = QtWidgets.QWidget(self.FrameLogin)
        self.widget_6.setGeometry(QtCore.QRect(300, 30, 411, 551))
        self.widget_6.setStyleSheet("background-color: rgb(198,48,48 );\n"
        "border-radius:20px;")
        self.widget_6.setObjectName("widget_6")
        self.label_41 = QtWidgets.QLabel(self.widget_6)
        self.label_41.setGeometry(QtCore.QRect(130, 40, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.etCodigo = QtWidgets.QLineEdit(self.widget_6)
        self.etCodigo.setGeometry(QtCore.QRect(50, 130, 321, 51))
        self.etCodigo.setStyleSheet("QLineEdit {\n"
        "      color: rgb(231, 231, 231);\n"
        "      font: 15pt \"Verdana\";\n"
        "      border: None;\n"
        "      border-bottom-color: white;\n"
        "      border-radius: 10px;\n"
        "      padding: 0 8px;\n"
        "      background: rgb(25, 25, 40);\n"
        "      selection-background-color: darkgray;\n"
        "}")
        self.etCodigo.setObjectName("etCodigo")
        self.etClave = QtWidgets.QLineEdit(self.widget_6)
        self.etClave.setGeometry(QtCore.QRect(50, 200, 321, 51))
        self.etClave.setStyleSheet("QLineEdit {\n"
        "      color: rgb(231, 231, 231);\n"
        "      font: 15pt \"Verdana\";\n"
        "      border: None;\n"
        "      border-bottom-color: white;\n"
        "      border-radius: 10px;\n"
        "      padding: 0 8px;\n"
        "      background: rgb(25, 25, 40);\n"
        "      selection-background-color: darkgray;\n"
        "}")
        self.etClave.setEchoMode(QtWidgets.QLineEdit.Password)
        self.etClave.setObjectName("etClave")
        self.btnAceptar = QtWidgets.QPushButton(self.widget_6)
        self.btnAceptar.setGeometry(QtCore.QRect(50, 280, 151, 51))
        self.btnAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAceptar.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 17pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "cursor:pointer;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnSalir = QtWidgets.QPushButton(self.widget_6)
        self.btnSalir.setGeometry(QtCore.QRect(220, 280, 151, 51))
        self.btnSalir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSalir.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 17pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnSalir.setObjectName("btnSalir")
        self.btnCodigoQr = QtWidgets.QPushButton(self.widget_6)
        self.btnCodigoQr.setGeometry(QtCore.QRect(50, 340, 321, 41))
        self.btnCodigoQr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCodigoQr.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 17pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnCodigoQr.setObjectName("btnCodigoQr")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setGeometry(QtCore.QRect(30, 450, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_43 = QtWidgets.QLabel(self.widget_6)
        self.label_43.setGeometry(QtCore.QRect(30, 510, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.widget_6)
        self.label_44.setGeometry(QtCore.QRect(30, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.etFecha = QtWidgets.QLabel(self.widget_6)
        self.etFecha.setGeometry(QtCore.QRect(110, 480, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etFecha.setFont(font)
        self.etFecha.setObjectName("etFecha")
        self.lcdHora = QtWidgets.QLCDNumber(self.widget_6)
        self.lcdHora.setGeometry(QtCore.QRect(90, 515, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(50)
        self.lcdHora.setFont(font)
        self.lcdHora.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdHora.setDigitCount(8)
        self.lcdHora.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdHora.setObjectName("lcdHora")
        self.lbProfesor = QtWidgets.QLabel(self.widget_6)
        self.lbProfesor.setGeometry(QtCore.QRect(110, 450, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbProfesor.setFont(font)
        self.lbProfesor.setObjectName("lbProfesor")
        self.btnCrearQR = QtWidgets.QPushButton(self.widget_6)
        self.btnCrearQR.setGeometry(QtCore.QRect(220, 510, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnCrearQR.setFont(font)
        self.btnCrearQR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCrearQR.setStyleSheet("QPushButton{\n"
        "color: rgb(231, 231, 231);\n"
        "font: 12pt \"Verdana\";\n"
        "border: 2px solid #FFB5B5;\n"
        "padding: 5px;\n"
        "border-radius: 3px;\n"
        "opacity: 200;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color: rgb(243, 40, 40);\n"
        "}\n"
        "")
        self.btnCrearQR.setObjectName("btnCrearQR")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.etFecha.setText(fecha_actual())
        #self.etHora.setText(time.strftime("%X"))
        #AGREGAR HORA DINAMINCA
        timer = QTimer(self.lcdHora)
        timer.timeout.connect(self.showTime)
        timer.start(1000)

        self.showTime()
        
        #-----------
        self.btnAceptar.clicked.connect(self.Validar)
        self.btnSalir.clicked.connect(self.salir)
        self.btnCodigoQr.clicked.connect(self.LoginQR)
        self.btnCrearQR.clicked.connect(self.CrearQR)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_41.setText(_translate("Dialog", "LOGIN"))
        self.etCodigo.setPlaceholderText(_translate("Dialog", "Código"))
        self.etClave.setPlaceholderText(_translate("Dialog", "Clave"))
        self.btnAceptar.setText(_translate("Dialog", "INGRESAR"))
        self.btnSalir.setText(_translate("Dialog", "SALIR"))
        self.btnCodigoQr.setText(_translate("Dialog", "INGRESAR POR QR"))
        self.label_2.setText(_translate("Dialog", "Profesor:"))
        self.label_43.setText(_translate("Dialog", "Hora:"))
        self.label_44.setText(_translate("Dialog", "Fecha:"))
        self.etFecha.setText(_translate("Dialog", "02/04/2021"))
        self.lbProfesor.setText(_translate("Dialog", "Cordova Nery, Teodoro Luciano"))
        self.btnCrearQR.setText(_translate("Dialog", "CREAR QR"))
    
    def showTime(self):
        time = QTime.currentTime()
        text = time.toString('hh:mm:ss')
        if (time.second() % 2) == 0:
            text =text[:2]+":"+text[3:]# + ' ' + text[:4]'''
        self.lcdHora.display(text)
    
    def Validar(self):
        cod = self.etCodigo.text()
        pas = self.etClave.text()
        validacion(cod, pas, self)
        self.etCodigo.setText("")
        self.etClave.setText("")
        #print(cod+"|"+pas)

    def LoginQR(self):
        logQR = IdentificadorImagen(None,None,"QR")
        if (logQR!="Falla"):
            if str(logQR).count("/")>0:
                lis = logQR.split("/")
                validacion(lis[0],lis[1],self)
        else:
            error_dialog.showMessage('Su cámara esta mal conectada o no conectada')
    
    def salir(self):
        #Dialog.close()
        os._exit(0)

    def CrearQR(self):
        self.crear = QtWidgets.QMainWindow()
        self.ui = Ui_Form_Crear()
        self.ui.setupUi(self.crear)
        self.crear.show()


def fecha_actual():
    now = datetime.now()
    if(now.day<10):dia = "0"+str(now.day)
    else:dia = now.day
    if(now.month<10):mes = "0"+str(now.month)
    else:mes = now.month
    return(str(dia)+"/"+str(mes)+"/"+str(now.year))

def validacion(cod, pas, self):
    lista = Query.login()
    # Verificacion de usuario docente y contraseña
    val = ""
    for i in lista:
        if (i[0] == str(cod) and i[2] == str(pas)):
            val = "correcto"
            Dialog.hide()
            self.menu = QtWidgets.QMainWindow()
            self.ui = Ui_Form()
            self.ui.setupUi(self.menu,i,Dialog)
            self.menu.show()
            
    if val != "correcto":
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText("Clave y usuario incorrecto!")
        #msg.setInformativeText('Código QR incorrecto')
        msg.setWindowTitle("AVISO")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()
        #wx.MessageDialog(None, "Clave y usuario incorrecto!", "Aviso", wx.OK | wx.ICON_WARNING).ShowModal()
    else:
        print("")
        #ventana.Hide()
        #cuando ingrese correctamente buscaremos si hay alguna seccion donde el docente este:'''



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
    '''app = QtWidgets.QApplication(sys.argv)
    ventana = Ui_Dialog()
    sys.exit(ventana.exec_())'''
